### ISSUE TITLE
Errore nella documentazione in README.md

### ISSUE THREAD

**Issue by paolo-giannelli** [progamma/cloud-connector#63]
Installando la versione 22.5 di Cloud Connector ed utilizzando Node.js in versione 12.17.0 come indicato dalle istruzioni di installazione quando si manda in esecuzione CloudSevber.js si riscontra il seguente errore:
```
C:\idc\public_html\cloudServer.js:268
  config.datamodels?.forEach(dm => this.createDataModel(dm));
             
SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:915:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:963:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:863:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:708:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
```
Utilizzando la versione 16.4.2 di Node.js funziona.
Occorre modificare README.md per indicare una versione minima diversa.

**Comment by matteosirri** [comment]
Ora nel readme si fa riferimento a Node 16 quindi si può chiudere.
